# Copyright 2021 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# For those usages not covered by the Apache License, Version 2.0 please
# contact: legal@canonical.com
#
# To get in touch with the maintainers, please contact:
# osm-charmers@lists.launchpad.net
##

options:
    advertised-hostname:
        description: Kafka Hostname
        type: string
        default: "kafka-k8s"
    advertised-port:
        description: Kafka port
        type: int
        default: 9092
    kafka-units:
        description: Kafka kafka-units
        type: int
        default: 1
    zookeeper-units:
        description: Zookeeper kafka-units
        type: int
        default: 1
    zookeeper-service-name:
        description: Zookeeper Service name
        type: string
        default: zookeeper-k8s-endpoints
    image:
        type: string
        description: OCI image
        default: rocks.canonical.com:443/wurstmeister/kafka:2.12-2.2.1
    num-partitions:
        description: Kafka number of partitions per topic
        type: int
        default: 1
