#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-kafka-exporter-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: osm-kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: osm-kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        imagePullPolicy: IfNotPresent
        args:
        - --kafka.server=kafka.osm.svc.cluster.local:9092
        - --web.listen-address=:9092
        ports:
        - name: metrics
          containerPort: 9092
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 10
#        resources:
#          limits:
#            cpu: 250m
#            memory: 192Mi
#          requests:
#            cpu: 100m
#            memory: 128Mi
#        securityContext:
#          allowPrivilegeEscalation: false
#          capabilities:
#            drop: ["all"]
#          readOnlyRootFilesystem: true
#          runAsGroup: 10000
#          runAsNonRoot: true
#          runAsUser: 10000
      terminationGracePeriodSeconds: 30
