# Copyright 2020 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
options:
  advertised-port:
    description: RO port
    type: int
    default: 9090
  vim_database:
    type: string
    description: "The database name."
    default: "mano_vim_db"
  ro_database:
    type: string
    description: "The database name."
    default: "mano_db"
  OPENMANO_TENANT:
    type: string
    description: "Openmano Tenant"
    default: "osm"
  image:
    type: string
    description: OCI image
    default: opensourcemano/ro:latest
  image_username:
    description: Docker repository username
    type: string
    default: ""
  image_password:
    description: Docker repository password
    type: string
    default: ""
  database_commonkey:
    description: Database common key
    type: string
    default: osm