{
 "title": "Hosts",
 "description": "Physical nodes dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "max(system_uptime)" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(system_n_cpus)" }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(mem_total)" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(irate(cpu_usage_system[$__rate_interval]) + irate(cpu_usage_user[$__rate_interval])) * 100",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "avg(irate(cpu_usage_iowait[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    { "expr": "avg(mem_used_percent)", "legendFormat": "Used RAM Memory" },
    {
     "expr": "avg(disk_used_percent{fstype=\"ext4\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    { "expr": "avg(swap_used_percent)", "legendFormat": "Used SWAP" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "system_load1", "legendFormat": "{{juju_unit}}_1m" },
      { "expr": "system_load5", "legendFormat": "{{juju_unit}}_5m" },
      { "expr": "system_load15", "legendFormat": "{{juju_unit}}_15m" }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(cpu_usage_system[30m])) by (juju_unit)",
       "legendFormat": "{{juju_unit}}_System"
      },
      {
       "expr": "avg(irate(cpu_usage_user[30m])) by (juju_unit)",
       "legendFormat": "{{juju_unit}}_User"
      },
      {
       "expr": "avg(irate(cpu_usage_iowait[30m])) by (juju_unit)",
       "legendFormat": "{{juju_unit}}_Iowait"
      },
      {
       "expr": "1 - avg(irate(cpu_usage_idle[30m])) by (juju_unit)",
       "legendFormat": "{{juju_unit}}_Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used  (EXT4/XFS)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "disk_free{fstype=\"ext4\"}"
      },
      {
       "expr": "disk_used_percent{fstype=\"ext4\"}"
      },
      {
       "expr": "disk_total{fstype=\"ext4\"}"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{name!~\"loop.*\"}[$__rate_interval])",
       "legendFormat": "{{juju_unit}}_{{name}}_Read bytes"
      },
      {
       "expr": "irate(diskio_write_bytes{name!~\"loop.*\"}[$__rate_interval])",
       "legendFormat": "{{juju_unit}}_{{name}}_Written bytes"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(diskio_io_time{name!~\"loop.*\"}[$__rate_interval])",
       "legendFormat": "{{juju_unit}}_{{name}}_ IO time"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "mem_total", "legendFormat": "{{juju_unit}}_Total" },
      { "expr": "mem_used", "legendFormat": "{{juju_unit}}_Used" },
      { "expr": "mem_available", "legendFormat": "{{juju_unit}}_Avaliable" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bps", "label": "transmit（-）/receive（+）" }
     ],
     "targets": [
      {
       "expr": "irate(net_bytes_recv{interface!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$__rate_interval])*8",
       "legendFormat": "{{juju_unit}}_{{interface}}_receive"
      },
      {
       "expr": "irate(net_bytes_sent{interface!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$__rate_interval])*8",
       "legendFormat": "{{instance}}_{{device}}_transmit"
      }
     ]
    },
    {
     "title": "Network Sockstat",
     "type": "graph",
     "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "netstat_tcp_established", "legendFormat": "{{juju_unit}}_CurrEstab" },
      { "expr": "sockstat_TCP_tw", "legendFormat": "{{juju_unit}}_TCP_tw" },
      { "expr": "sockstat_sockets_used", "legendFormat": "{{juju_unit}}_Sockets_used" },
      { "expr": "sockstat_UDP_inuse", "legendFormat": "{{juju_unit}}_UDP_inuse" },
      { "expr": "sockstat_TCP_alloc", "legendFormat": "{{juju_unit}}_TCP_alloc" }
     ]
    }
   ]
  }
 ]
}